# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f9c8158a60e8fc20b2f17d875eb65e3bf12a3f5dd26b3f0e6033610d1117934bc8c4327030b4323c89b8ee332baebad39afa873427217752cc183d4774b268f

test:
  secret_key_base: ae72057dea2de545e34d7f84968f75e6ad3f47100a55847812bae10b9f8109fcb79406f3f56b5f5ec172cc513ac791217945e0c9e3afd586a01b7eb49c2ddd69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
